server:
  port: 8101

spring:
  application:
    name: yf-exam
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:zs_exam}?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PWD:root}

  # Redis配置
  redis:
    database: 0
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    timeout: 5000

# 日志级别
logging:
  level:
    root: debug
