version: '3.1'

services:

  nginx:
    image: nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./exam-vue/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8150:80"
    depends_on:
      - backend

  backend:
    image: openjdk:11.0.12-jdk
    restart: always
    working_dir: /app
    environment:
      TZ: Asia/Shanghai
      REDIS_HOST: redis
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: el_exam
      DB_USER: root
      DB_PWD: root
    volumes:
      - ./exam-api/target/exam-api.jar:/app/app.jar:rw
    entrypoint: java -jar app.jar
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
#    restart: always
    ports:
      - 8152:8080

  redis:
    image: "redis:alpine"
